config/routes.rb
Rails.application.routes.draw do

  root to: 'task#index'

  get  '/login'  => 'auth#new'   , as: 'login'
  post '/login'  => 'auth#create', as: 'auth'
  post '/logout' => 'auth#delete', as: 'logout'

  get    '/user'          => 'user#index' , as: 'users'
  post   '/user'          => 'user#create', as: ''
  get    '/user/new'      => 'user#new'   , as: 'new_user'
  get    '/user/:id/edit' => 'user#edit'  , as: 'edit_user'
  put    '/user/:id'      => 'user#update', as: 'user'
  patch  '/user/:id'      => 'user#update', as: ''
  delete '/user/:id'      => 'user#delete', as: ''

  get     '/task'             => 'task#index'  , as: 'tasks'
  post    '/task'             => 'task#create' , as: ''
  get     '/task/:id'         => 'task#update' , as: 'task'
  delete  '/task/:id'         => 'task#delete' , as: ''
  get     '/task/:id/content' => 'task#content', as: 'content_task'
  patch   '/task/:id/'        => 'task#save' , as: ''

end

app/models/priority.rb
class Priority < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :priority

  scope :active, -> (cond,id) {
    return where(:user_id => id, :completed => false, :deleted => false) if cond == 1
    return where(:user_id => id, :completed => true, :deleted => false) if cond == 2
    return where(:user_id => id, :deleted => false)
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  EMAILCHECK = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :mail, presence: true, length: {maximum: 60}, format: {with: EMAILCHECK }, uniqueness: true
  validates :name, presence: true, length: {maximum: 60}
  validates :password, confirmation: true, presence: true, length: {minimum: 8}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def not_authenticated
    redirect_to login_path
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  skip_before_filter :require_login, except: [:delete]
  def new
  end

  def create
    @user = login(params[:mail], params[:password])
    if @user
      redirect_to tasks_path
    else
      flash.now[:alert] = "ログイン失敗"
      render :new
    end
  end

  def delete
    logout
    redirect_to login_path
  end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  def index
    @task = Task.new
    cond = params[:condition] || session[:condition] || 1
    cond = cond.to_i
    @cond1 = (cond == 1)
    @cond2 = (cond == 2)
    @cond3 = (cond == 3)
    id = params[:user]
    @trainee = User.where(trainer_id: current_user.id).first
    if @trainee.nil?
    @mytasks = Task.order("priority_id").active(cond,current_user.id)
    else
    t_id = @trainee.id
    @mytasks = Task.order("priority_id").active(cond,current_user.id)
    @traineetasks = Task.order("priority_id").active(cond,t_id)
    end 
    session[:condition] = cond
  end

  def create
    task_params = params[:task]
    @task = Task.new
    @task.user = User.find(task_params[:user])
    @task.completed = false
    @task.priority = Priority.find(task_params[:priority])
    @task.description = task_params[:description]
    @task.deleted = false
    if @task.save
      session[:condition] = 1
      redirect_to :tasks
    else
      @tasks = Task.active(session[:condition],current_user.id)
      render :index
    end
  end

  def update
    @task = Task.find(params[:id])
    @task.completed = !@task.completed
    @task.save
    redirect_to :tasks
  end

  def delete
    @task = Task.find(params[:id])
    @task.deleted = true
    @task.save
    redirect_to :tasks
  end
  
  def content 
    @task = Task.find(params[:id])
  end

  def save
    task_params = params[:task]
    @task = Task.find(params[:id])
    @task.contents = task_params[:contents]
    if @task.save
      redirect_to :tasks
    else
      render :content
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  skip_before_filter :require_login, only: [:index, :new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    user_params = params.require(:user).permit(
      :mail,
      :name,
      :trainer_id,
      :password,
      :password_confirmation
    )
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render :new
    end
  end

  def update
    user_params = params.require(:user).permit(
      :mail,
      :name,
      :trainer_id,
      :password,
      :password_confimation 
    )
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
     redirect_to edit_user_path 
    else
     render :edit
    end
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar nabvar-fixed-top navbar-inverse">
<div class="navbar-inner">
  <div class="container">
  <%= link_to 'ToDoリスト', :root, :class => "navbar-brand" %>
    <nav>
    <table class="nav pull-right" style="margin-top:30px">
      <tr>
        <td>
          <% if current_user %>
            <%= link_to current_user.name, edit_user_path(current_user), :class => "btn btn-link" %> |
            <%= link_to 'ログアウト', logout_path, method: :post, :class => "btn btn-link" %>
          <% else %>
            <%= link_to '登録', new_user_path, :class => "btn btn-link" %> | 
            <%= link_to 'ログイン', login_path, :class => "btn btn-link" %>
          <% end %>
        </td>
      </tr>
    </table>
    </nav>
  </div>
</div>
</header>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/task/content.html.erb
<% if @task.errors.any? %>
  <div id="error_explanation">
    <h2><%= @task.errors.count %>件のエラーが発生しました。</h2>
    <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for(@task) do |f| %>
  <table class="usertable">
    <tr>
      <td>
        <h3><%= @task.description %></h3>
      </td>
      <td id="b"><%= f.submit '保存', method: :patch, :class => "btn btn-primary" %></td>
    </tr>
    <tr>
      <td>
        <%= f.text_area :contents, :size => "120x30", :maxlength => "2000", :class => "form-control" %>
      </td>
    </tr>
  </table>
<% end %>

app/views/task/index.html.erb
<div>
  <%= form_for(@task) do |f| %>
    <table>
      <tr>
        <td style="padding:20px 20px 0px 0px"><%= f.label :description, 'タスク', :class => "lead" %></td>
        <td style="padding:20px 20px 0px 0px"><%= f.label :priority, '優先度', :class => "lead" %></td>
        <td style="padding:20px 20px 0px 0px"><%= f.label :user, '担当者', :class => "lead" %></td>
        <td></td>
      </tr>
      <tr>
        <td style="padding:5px 20px 0px 0px"><%= f.text_field :description, :class => "form-control", :size => "30" %></td>
        <td style="padding:5px 20px 0px 0px"><%= f.select :priority, Priority.all.map{|t| [t.name, t.id]}, {}, { class: "form-control" } %></td>
        <td style="padding:5px 20px 0px 0px"><%= f.select :user, User.where(["trainer_id = ? or id = ?", current_user.id,current_user.id]).map{|t| [t.name, t.id]}, {}, { class: "form-control" } %></td>
        <td style="padding:5px 20px 0px 0px"><%= f.submit '登録', :class => "form-control" %></td>
      </tr>
    </table>
  <% end %>
</div>

<hr>
<%= form_tag('/task', method: :get, id: "condition") do %>
  <%= radio_button_tag("condition", 1, @cond1 || true, id: :cond1) %> <%= label_tag("cond1", "残存", :class => "lead") %>
  <%= radio_button_tag("condition", 2, @cond2 || false, id: :cond2) %> <%= label_tag("cond2", "完了", :class => "lead") %>
  <%= radio_button_tag("condition", 3, @cond3 || false, id: :cond3) %> <%= label_tag("cond3", "全件", :class => "lead") %>
<% end %>

<% if @mytasks.empty? %>
  <p>taskはありません</p>
<% else %>
  <table class="tasktable">
   <% @mytasks.each do |task| %>
    <tr>
      <td><input type="checkbox" id="chk<%= task.id %>" <%= task.completed ? 'checked' : '' %> onClick="Turbolinks.visit('/task/<%= task.id %>')"></td>
      <td><%= task.priority.name %></td>
      <td><%= task.user.name %></td>
      <td><%= link_to task.description, controller: "task", action: "content", id: task %></td>
      <td><%= link_to '削除', task, method: :delete, data:{ confirm: '削除しますか？'}, :class => "btn btn-danger btn-sm" %></td>
    </tr>
  <% end %>
<% if @traineetasks.nil? %>
  <p>トレーニのtaskはありません</p>
<% else %>
  <% @traineetasks.each do |ttask| %>
   <tr>
     <td><input type="checkbox" id="chk<%= ttask.id %>" <%= ttask.completed ? 'checked' : '' %> onClick="Turbolinks.visit('/task/<%= ttask.id %>')"></td>
     <td><%= ttask.priority.name %></td>
     <td><%= ttask.user.name %></td>
     <td><%= link_to  ttask.description, controller: "task", action: "content", id: ttask %></td>
     <td><%= link_to '削除', ttask, method: :delete, data:{ confirm: '削除しますか？'}, :class => "btn btn-danger btn-sm" %></td>
   </tr>
  <% end %>
  </table>
<% end %>
<% end %>

<script>
  $(function(){
    $('input[name=condition]').change(function(){
       $('form#condition').submit();
    });
  });
</script>    

app/views/user/edit.html.erb
<h1>ユーザ情報変更</h1>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーが発生しました。</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table class="usertable">
    <tr>
      <td><%= f.label :mail, 'メール', :class => "lead" %></td>
      <td><%= f.text_field :mail, :class => "form-control", :size => "30" %></td>
    </tr>
    <tr>
      <td><%= f.label :name, '名称', :class => "lead" %></td>
      <td><%= f.text_field :name, :class => "form-control", :size => "30" %></td>
    </tr>
    <tr>
      <td><%= f.label :trainer_id, 'トレーナー', :class => "lead" %></td>
      <td><%= f.select :trainer_id, User.where.not(id: params[:id]).map{|t| [t.name, t.id]}, { :include_blank => true }, { class: "form-control" } %></td>
    </tr>
    <tr>
      <td><%= f.label :password, 'パスワード', :class => "lead" %></td>
      <td><%= f.password_field :password, :class => "form-control" %></td>
    </tr>
    <tr>
      <td><%= f.label :password_confirmation, 'パスワード(2回目)', :class => "lead" %></td>
      <td><%= f.password_field :password_confirmation, :class => "form-control" %></td>
    </tr>
    <tr>
      <td id="b" colspan="2"><%= f.submit '変更', method: :put, :class => "form-control" %></td>
    </tr>
  </table>
<% end %>

app/views/user/index.html.erb
<h1>ユーザ一覧</h1>
<% if @users.empty? %>
  <p>ユーザはいません。</p>
<% else %>
  <table>
    <tr>
      <th>メール</th>
      <th>名称</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.mail %></td>
        <td><%= user.name %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/user/new.html.erb
<h1>ユーザ登録</h1>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーが発生しました。</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table class="usertable">
    <tr>
      <td><%= f.label :mail, 'メール', :class => "lead" %></td>
      <td><%= f.text_field :mail, :class => "form-control", :size => "30" %></td>
    </tr>
    <tr>
      <td><%= f.label :name, '名称', :class => "lead" %></td>
      <td><%= f.text_field :name, :class => "form-control", :size => "30" %></td>
    </tr>
    <tr>
      <td><%= f.label :trainer_id, 'トレーナー', :class => "lead" %></td>
      <td><%= f.select :trainer_id, User.all.map{|t| [t.name, t.id]}, { :include_blank => true }, { class: "form-control" } %></td>
    </tr>
    <tr>
      <td><%= f.label :password, 'パスワード', :class => "lead" %></td>
      <td><%= f.password_field :password, :class => "form-control", :size => "30" %></td>
    </tr>
    <tr>
      <td><%= f.label :password_confirmation, 'パスワード(2回目)', :class => "lead" %></td>
      <td><%= f.password_field :password_confirmation, :class => "form-control", :size => "30" %></td>
    </tr>
    <tr>
      <td id="b" colspan="2"><%= f.submit '登録', :class => "btn btn-default btn-block" %></td>
    </tr>
  </table>
<% end %>